# Import Required Libraries

In [154]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Loading Data

In [155]:
data=pd.read_csv(r'C:\Users\Arun\DEPLOYMENT\Feature Engineering\Categorical Encoding Techniques\One Hot Categorical Encoding\houseprice1.csv',usecols=['Neighborhood', 'Exterior1st', 'Exterior2nd','SalePrice'])

In [156]:
data.head()

  Neighborhood Exterior1st Exterior2nd  SalePrice
0      CollgCr     VinylSd     VinylSd     208500
1      Veenker     MetalSd     MetalSd     181500
2      CollgCr     VinylSd     VinylSd     223500
3      Crawfor     Wd Sdng     Wd Shng     140000
4      NoRidge     VinylSd     VinylSd     250000

In [157]:
from sklearn.model_selection import train_test_split

# Dividing Data Set into Dependent and Independent Variables

In [158]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [159]:
x.head()

  Neighborhood Exterior1st Exterior2nd
0      CollgCr     VinylSd     VinylSd
1      Veenker     MetalSd     MetalSd
2      CollgCr     VinylSd     VinylSd
3      Crawfor     Wd Sdng     Wd Shng
4      NoRidge     VinylSd     VinylSd

In [160]:
y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

# Splitting Data into Training and Test Set

In [161]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

# Implementing One Hot Encoding Using feature-engine

In [162]:
from feature_engine import categorical_encoders as ce

In [163]:
ohe=ce.OneHotCategoricalEncoder(top_categories=None,drop_last=True)

In [164]:
ohe.fit(x_train)

OneHotCategoricalEncoder(drop_last=True,
                         variables=['Neighborhood', 'Exterior1st',
                                    'Exterior2nd'])

In [165]:
x_train=ohe.transform(x_train)
x_test=ohe.transform(x_test)

In [166]:
x_train.head()

,Neighborhood_Edwards,Neighborhood_OldTown,Neighborhood_CollgCr,Neighborhood_SawyerW,Neighborhood_Gilbert,Neighborhood_NAmes,Neighborhood_Mitchel,Neighborhood_NWAmes,Neighborhood_Somerst,Neighborhood_IDOTRR,...,Exterior2nd_AsphShn,Exterior2nd_Wd Shng,Exterior2nd_Brk Cmn,Exterior2nd_AsbShng,Exterior2nd_CmentBd,Exterior2nd_ImStucc,Exterior2nd_Stucco,Exterior2nd_BrkFace,Exterior2nd_Stone,Exterior2nd_CBlock
921,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
520,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
401,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
280,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1401,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [167]:
x_test.head()

,Neighborhood_Edwards,Neighborhood_OldTown,Neighborhood_CollgCr,Neighborhood_SawyerW,Neighborhood_Gilbert,Neighborhood_NAmes,Neighborhood_Mitchel,Neighborhood_NWAmes,Neighborhood_Somerst,Neighborhood_IDOTRR,...,Exterior2nd_AsphShn,Exterior2nd_Wd Shng,Exterior2nd_Brk Cmn,Exterior2nd_AsbShng,Exterior2nd_CmentBd,Exterior2nd_ImStucc,Exterior2nd_Stucco,Exterior2nd_BrkFace,Exterior2nd_Stone,Exterior2nd_CBlock
258,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
267,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
288,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
649,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1233,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [168]:
ohe.variables

['Neighborhood', 'Exterior1st', 'Exterior2nd']

In [169]:
x_train1,x_test1,y_train1,y_test1=train_test_split(x,y,test_size=0.2,random_state=1)

# Implementing One Hot Encoding Only for Particular Variable

In [170]:
ohe1=ce.OneHotCategoricalEncoder(top_categories=None,drop_last=True,variables=['Neighborhood'])

In [171]:
ohe1.fit(x_train1)

OneHotCategoricalEncoder(drop_last=True, variables=['Neighborhood'])

In [172]:
x_train1=ohe1.transform(x_train1)
x_test1=ohe1.transform(x_test1)

In [173]:
x_train1.head()

,Exterior1st,Exterior2nd,Neighborhood_Edwards,Neighborhood_OldTown,Neighborhood_CollgCr,Neighborhood_SawyerW,Neighborhood_Gilbert,Neighborhood_NAmes,Neighborhood_Mitchel,Neighborhood_NWAmes,...,Neighborhood_Blmngtn,Neighborhood_NoRidge,Neighborhood_BrkSide,Neighborhood_Sawyer,Neighborhood_BrDale,Neighborhood_MeadowV,Neighborhood_Timber,Neighborhood_ClearCr,Neighborhood_SWISU,Neighborhood_Veenker
921,MetalSd,MetalSd,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
520,MetalSd,MetalSd,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
401,VinylSd,VinylSd,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
280,Plywood,Plywood,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1401,VinylSd,VinylSd,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [174]:
x_test1.head()

,Exterior1st,Exterior2nd,Neighborhood_Edwards,Neighborhood_OldTown,Neighborhood_CollgCr,Neighborhood_SawyerW,Neighborhood_Gilbert,Neighborhood_NAmes,Neighborhood_Mitchel,Neighborhood_NWAmes,...,Neighborhood_Blmngtn,Neighborhood_NoRidge,Neighborhood_BrkSide,Neighborhood_Sawyer,Neighborhood_BrDale,Neighborhood_MeadowV,Neighborhood_Timber,Neighborhood_ClearCr,Neighborhood_SWISU,Neighborhood_Veenker
258,VinylSd,VinylSd,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
267,Wd Sdng,Wd Sdng,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
288,MetalSd,MetalSd,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
649,CemntBd,CmentBd,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1233,Plywood,Plywood,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [175]:
ohe1.variables

['Neighborhood']

In [176]:
x_train2,x_test2,y_train2,y_test2=train_test_split(x,y,test_size=0.2,random_state=1)

# Implementing One Hot Encoding For Most Frequent Categories

In [177]:
ohe2=ce.OneHotCategoricalEncoder(top_categories=10)

In [178]:
ohe2.fit(x_train2)

OneHotCategoricalEncoder(top_categories=10,
                         variables=['Neighborhood', 'Exterior1st',
                                    'Exterior2nd'])

In [179]:
x_train2=ohe2.transform(x_train2)
x_test2=ohe2.transform(x_test2)

In [180]:
x_train2.head()

,Neighborhood_NAmes,Neighborhood_CollgCr,Neighborhood_OldTown,Neighborhood_Edwards,Neighborhood_Somerst,Neighborhood_NridgHt,Neighborhood_Gilbert,Neighborhood_NWAmes,Neighborhood_Sawyer,Neighborhood_BrkSide,...,Exterior2nd_VinylSd,Exterior2nd_MetalSd,Exterior2nd_HdBoard,Exterior2nd_Wd Sdng,Exterior2nd_Plywood,Exterior2nd_CmentBd,Exterior2nd_Wd Shng,Exterior2nd_Stucco,Exterior2nd_BrkFace,Exterior2nd_AsbShng
921,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
520,0,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
401,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
280,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1401,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [181]:
x_test2.head()

,Neighborhood_NAmes,Neighborhood_CollgCr,Neighborhood_OldTown,Neighborhood_Edwards,Neighborhood_Somerst,Neighborhood_NridgHt,Neighborhood_Gilbert,Neighborhood_NWAmes,Neighborhood_Sawyer,Neighborhood_BrkSide,...,Exterior2nd_VinylSd,Exterior2nd_MetalSd,Exterior2nd_HdBoard,Exterior2nd_Wd Sdng,Exterior2nd_Plywood,Exterior2nd_CmentBd,Exterior2nd_Wd Shng,Exterior2nd_Stucco,Exterior2nd_BrkFace,Exterior2nd_AsbShng
258,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
267,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
288,0,0,0,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
649,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1233,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [182]:
ohe2.encoder_dict_

{'Neighborhood': ['NAmes',
  'CollgCr',
  'OldTown',
  'Edwards',
  'Somerst',
  'NridgHt',
  'Gilbert',
  'NWAmes',
  'Sawyer',
  'BrkSide'],
 'Exterior1st': ['VinylSd',
  'MetalSd',
  'HdBoard',
  'Wd Sdng',
  'Plywood',
  'CemntBd',
  'BrkFace',
  'Stucco',
  'WdShing',
  'AsbShng'],
 'Exterior2nd': ['VinylSd',
  'MetalSd',
  'HdBoard',
  'Wd Sdng',
  'Plywood',
  'CmentBd',
  'Wd Shng',
  'Stucco',
  'BrkFace',
  'AsbShng']}